FROM node:14 as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG API_URI
ARG SENTRY_DSN
ARG SENTRY_APM
ARG DEMO_MODE
ARG GTM_ID
ENV API_URI ${API_URI:-http://localhost:8000/graphql/}
RUN API_URI=${API_URI} npm run build:export

FROM nginx:stable
WORKDIR /app
COPY ./nginx/prod.conf /etc/nginx/conf.d/prod.conf
COPY --from=builder /app/dist/ /app/
